spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/deanoffice-student-mobile
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: admin
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
server.port: 8075
