INSERT INTO application_type(name) VALUES ('Навчання за індивідуальним графіком');
INSERT INTO application_type(name) VALUES ('Перескладання іспиту для підвищення оцінки з метою отримання диплому з відзнакою');
INSERT INTO application_type(name) VALUES ('Поновлення до складу здобувачів вищої освіти після відрахування');
INSERT INTO application_type(name) VALUES ('Участь в конкурсі для переведення на вакантне місце навчання за рахунок коштів державного бюджету');
INSERT INTO application_type(name) VALUES ('Надання академічної відпустки');
INSERT INTO application_type(name) VALUES ('Зміна ім''я/прізвища');
INSERT INTO application_type(name) VALUES ('Поновлення до складу здобувачів вищої освіти після академічної відпустки');
INSERT INTO application_type(name) VALUES ('Відрахування за власним бажанням');
INSERT INTO application_type(name) VALUES ('Відмова від соціальної/академічної стипендії на користь академічної/соціальної');
INSERT INTO application_type(name) VALUES ('Переведення з денної/заочної форми навчання на заочну/денну');
INSERT INTO application_type(name) VALUES ('Переведення на навчання за іншою освітньою програмою');
INSERT INTO application_type(name) VALUES ('Переведення на навчання до іншого навчального закладу');